# Site wide configuration

title: 
locale: en_US
description: Crafting technology solutions and creating value for clients around the world
logo: dc-logo-color.png
search: false
url: http://dotsconnect.us

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Tim Welch
  avatar: bio1b.jpeg
  email: tim.j.welch@gmail.com
  disqus-shortname:
  twitter: tdoubleuu
  facebook: #username
  github: twelch
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: timjwelch
  instagram: dotsconnect
  skype: tim.j.welch
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-50551462-1
    verify:
    ad-client:
    ad-slot:
  bing-verify: 5FA08EFEFC9BA0775DA9F386E8D1C8C4
